services:
  registry:
    image: registry:2
    environment:
      REGISTRY_AUTH: htpasswd
      REGISTRY_AUTH_HTPASSWD_REALM: Realm
      REGISTRY_AUTH_HTPASSWD_PATH: /auth/htpasswd
    restart: always
    ports:
      - "5000:5000"
    volumes:
      - ./htpasswd:/auth/htpasswd
      - /mnt/registry/registry:/var/lib/registry

  cache-registry:
    image: registry:2
    restart: always
    environment:
      REGISTRY_PROXY_REMOTEURL: https://registry-1.docker.io
      REGISTRY_STORAGE_DELETE_ENABLED: 1
    ports:
      - "5001:5000"
    volumes:
      - /mnt/registry/cache-registry:/var/lib/registry

volumes:
  registry:
  cache-registry: